version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: skylytics_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: skylytics
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    
  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"